import { at } from "../indexing.js";
import { createDiggerMap } from "../map/digger.js";
import { getRoomCenter } from "../map/features.js";
import { encodePointKey } from "../pointkey.js";
import { createRng, type Rng } from "../rng.js";
import {
	BAT_COUNT_PER_FLOOR,
	ENEMY_MAX_HP,
	POTION_COUNT_PER_FLOOR,
	ZOMBIE_COUNT_PER_FLOOR,
} from "./balance.js";
import { buildEmptyColumns, buildUnexploredColumns } from "./columns.js";
import { buildEventLog } from "./events.js";
import type { Enemy, GameState, Item, Position } from "./state.js";
import { computeVisiblePoints, deriveExploredState } from "./vision.js";

/** Everything one dungeon floor is made of, before it becomes game state. */
export interface FloorLayout {
	readonly terrain: number[][];
	readonly player: Position;
	readonly enemies: readonly Enemy[];
	readonly items: readonly Item[];
	readonly stairs: Position;
}

/** One random tile out of the pool, removed from it (no tile spawns twice). */
const drawSpawnTile = (pool: Position[], rng: Rng): Position => {
	const index = rng.getUniformInt(0, pool.length - 1);
	const picked = at(pool, index);
	pool.splice(index, 1);
	return picked;
};

/**
 * Floor tiles usable for spawning things away from the player: outside the
 * starting field of view when possible (nothing pops up on screen at turn
 * one), any floor tile except the player's own otherwise (tiny fully-visible
 * maps). Room-independent on purpose: digger occasionally produces a
 * single-room, corridor-heavy dungeon.
 */
const collectSpawnPool = (
	terrain: GameState["terrain"],
	player: Position,
): Position[] => {
	const visiblePoints = computeVisiblePoints(terrain, player);
	const collectFloorTiles = (outOfSightOnly: boolean): Position[] => {
		const tiles: Position[] = [];
		for (let x = 0; x < terrain.length; x++) {
			const column = terrain[x] ?? [];
			for (let y = 0; y < column.length; y++) {
				if (column[y] !== 0) {
					continue;
				}
				if (x === player.x && y === player.y) {
					continue;
				}
				if (outOfSightOnly && visiblePoints.has(encodePointKey(x, y))) {
					continue;
				}
				tiles.push({ x, y });
			}
		}
		return tiles;
	};

	const candidates = collectFloorTiles(true);
	return candidates.length > 0 ? candidates : collectFloorTiles(false);
};

/**
 * One dungeon floor, generated by consuming (and thereby advancing) `rng`:
 * digger terrain, the player at the center of the first room,
 * ZOMBIE_COUNT_PER_FLOOR zombies, BAT_COUNT_PER_FLOOR bats, the down
 * staircase and POTION_COUNT_PER_FLOOR potions drawn from the spawn pool.
 * Nothing shares a tile with anything else unless the pool ran dry (tiny
 * fully-visible maps).
 */
export const buildFloorLayout = (
	width: number,
	height: number,
	rng: Rng,
): FloorLayout => {
	const columns = buildEmptyColumns(width);
	const dungeon = createDiggerMap(width, height, rng).create((x, y, value) => {
		at(columns, x)[y] = value;
	});

	const firstRoom = dungeon.getRooms()[0];
	if (firstRoom === undefined) {
		throw new Error("unreachable: digger always digs at least one room");
	}
	const [playerX, playerY] = getRoomCenter(firstRoom);
	const player: Position = { x: playerX, y: playerY };

	const pool = collectSpawnPool(columns, player);
	const enemies: Enemy[] = [];
	for (let i = 0; i < ZOMBIE_COUNT_PER_FLOOR && pool.length > 0; i++) {
		enemies.push({
			...drawSpawnTile(pool, rng),
			kind: "zombie",
			hp: ENEMY_MAX_HP.zombie,
		});
	}
	for (let i = 0; i < BAT_COUNT_PER_FLOOR && pool.length > 0; i++) {
		enemies.push({
			...drawSpawnTile(pool, rng),
			kind: "bat",
			hp: ENEMY_MAX_HP.bat,
		});
	}

	const remaining = pool.length > 0 ? pool : collectSpawnPool(columns, player);
	const stairs = drawSpawnTile(remaining, rng);

	const items: Item[] = [];
	for (let i = 0; i < POTION_COUNT_PER_FLOOR && remaining.length > 0; i++) {
		items.push({ ...drawSpawnTile(remaining, rng), kind: "potion" });
	}

	return { terrain: columns, player, enemies, items, stairs };
};

/**
 * The next floor down, generated from the state's own RNG so a whole
 * multi-floor run stays reproducible from (dimensions, seed) alone. HP, the
 * event log and the floor counter carry over; terrain, enemies, staircase
 * and the explored grid start fresh. Pure: deterministic in its argument.
 */
export const descendStairs = (state: GameState): GameState => {
	const rng = createRng(1).setState(state.rng);
	const layout = buildFloorLayout(state.width, state.height, rng);
	const nextFloor = state.floor + 1;
	return deriveExploredState({
		...state,
		terrain: layout.terrain,
		explored: buildUnexploredColumns(state.width, state.height),
		player: layout.player,
		enemies: layout.enemies,
		items: layout.items,
		stairs: layout.stairs,
		events: buildEventLog(state.events, [
			{ type: "floor-descended", payload: { floor: nextFloor } },
		]),
		rng: rng.getState(),
		floor: nextFloor,
	});
};
