import { at } from "../indexing.js";
import { createDiggerMap } from "../map/digger.js";
import { getRoomCenter } from "../map/features.js";
import { encodePointKey } from "../pointkey.js";
import { createRng, type Rng } from "../rng.js";
import { ZOMBIE_MAX_HP } from "./balance.js";
import { buildEmptyColumns, buildUnexploredColumns } from "./columns.js";
import { buildEventLog } from "./events.js";
import type { Enemy, GameState, Position } from "./state.js";
import { computeVisiblePoints, deriveExploredState } from "./vision.js";

const ENEMY_COUNT = 3;

/** Everything one dungeon floor is made of, before it becomes game state. */
export interface FloorLayout {
	readonly terrain: number[][];
	readonly player: Position;
	readonly enemies: readonly Enemy[];
	readonly stairs: Position;
}

/**
 * Floor tiles usable for spawning things away from the player: outside the
 * starting field of view when possible (nothing pops up on screen at turn
 * one), any floor tile except the player's own otherwise (tiny fully-visible
 * maps). Room-independent on purpose: digger occasionally produces a
 * single-room, corridor-heavy dungeon.
 */
const collectSpawnPool = (
	terrain: GameState["terrain"],
	player: Position,
): Position[] => {
	const visiblePoints = computeVisiblePoints(terrain, player);
	const collectFloorTiles = (outOfSightOnly: boolean): Position[] => {
		const tiles: Position[] = [];
		for (let x = 0; x < terrain.length; x++) {
			const column = terrain[x] ?? [];
			for (let y = 0; y < column.length; y++) {
				if (column[y] !== 0) {
					continue;
				}
				if (x === player.x && y === player.y) {
					continue;
				}
				if (outOfSightOnly && visiblePoints.has(encodePointKey(x, y))) {
					continue;
				}
				tiles.push({ x, y });
			}
		}
		return tiles;
	};

	const candidates = collectFloorTiles(true);
	return candidates.length > 0 ? candidates : collectFloorTiles(false);
};

/**
 * One dungeon floor, generated by consuming (and thereby advancing) `rng`:
 * digger terrain, the player at the center of the first room, ENEMY_COUNT
 * zombies and the down staircase drawn from the spawn pool. The staircase
 * never shares a tile with the player or an enemy unless the pool ran dry.
 */
export const buildFloorLayout = (
	width: number,
	height: number,
	rng: Rng,
): FloorLayout => {
	const columns = buildEmptyColumns(width);
	const dungeon = createDiggerMap(width, height, rng).create((x, y, value) => {
		at(columns, x)[y] = value;
	});

	const firstRoom = dungeon.getRooms()[0];
	if (firstRoom === undefined) {
		throw new Error("unreachable: digger always digs at least one room");
	}
	const [playerX, playerY] = getRoomCenter(firstRoom);
	const player: Position = { x: playerX, y: playerY };

	const pool = collectSpawnPool(columns, player);
	const enemies: Enemy[] = [];
	for (let i = 0; i < ENEMY_COUNT && pool.length > 0; i++) {
		const index = rng.getUniformInt(0, pool.length - 1);
		enemies.push({ ...at(pool, index), kind: "zombie", hp: ZOMBIE_MAX_HP });
		pool.splice(index, 1);
	}

	const stairsPool = pool.length > 0 ? pool : collectSpawnPool(columns, player);
	const stairs = at(stairsPool, rng.getUniformInt(0, stairsPool.length - 1));

	return { terrain: columns, player, enemies, stairs };
};

/**
 * The next floor down, generated from the state's own RNG so a whole
 * multi-floor run stays reproducible from (dimensions, seed) alone. HP, the
 * event log and the floor counter carry over; terrain, enemies, staircase
 * and the explored grid start fresh. Pure: deterministic in its argument.
 */
export const descendStairs = (state: GameState): GameState => {
	const rng = createRng(1).setState(state.rng);
	const layout = buildFloorLayout(state.width, state.height, rng);
	const nextFloor = state.floor + 1;
	return deriveExploredState({
		...state,
		terrain: layout.terrain,
		explored: buildUnexploredColumns(state.width, state.height),
		player: layout.player,
		enemies: layout.enemies,
		stairs: layout.stairs,
		events: buildEventLog(state.events, [
			{ type: "floor-descended", payload: { floor: nextFloor } },
		]),
		rng: rng.getState(),
		floor: nextFloor,
	});
};
