import {
	ENEMY_ACTIONS_PER_TURN,
	ENEMY_ATTACK_DAMAGE,
	ENEMY_EXPERIENCE_REWARD,
	ENEMY_MAX_HP,
} from "../../game/balance.js";
import {
	ENEMY_KIND_VALUES,
	ITEM_KIND_VALUES,
	TRAP_KIND_VALUES,
} from "../../game/events.js";
import { ENEMY_GLYPHS, ITEM_GLYPHS } from "../../game/glyphs.js";
import {
	ENEMY_NAMES,
	resolveItemDisplayName,
	TRAP_NAMES,
} from "../gameNames.js";
import {
	ENEMY_CATALOG,
	type ItemCategory,
	type SpawnInfo,
	TRAP_CATALOG,
} from "./catalogData.js";
import { ITEM_CATALOG } from "./itemCatalog.js";

// Builds docs/catalog.md from the same tables the game runs on (balance.ts,
// glyphs.ts, gameNames.ts, catalogData.ts). Freshness is enforced by
// catalog.test.ts: the committed file must equal this function's output, so
// forgetting to regenerate after a balance change fails `npm test`.
// Regenerate with `npm run docs:catalog`.

const CATEGORY_ORDER: readonly ItemCategory[] = [
	"薬",
	"巻物",
	"杖",
	"指輪",
	"装備",
	"食料",
];

const formatSpawn = (spawn: SpawnInfo): string => {
	switch (spawn.type) {
		case "guaranteed":
			return `確定${spawn.countPerFloor}個/フロア`;
		case "chance":
			return `${spawn.percent}%/フロア`;
		case "scaling":
			return `${spawn.base}体+${spawn.growthInterval}フロアごとに1体(最大${spawn.max})`;
	}
};

const buildEnemySection = (): string => {
	const rows = ENEMY_KIND_VALUES.map((kind) => {
		const entry = ENEMY_CATALOG[kind];
		return `| ${ENEMY_GLYPHS[kind].glyph} | ${ENEMY_NAMES[kind]} | ${ENEMY_MAX_HP[kind]} | ${ENEMY_ATTACK_DAMAGE[kind]} | ${ENEMY_ACTIONS_PER_TURN[kind]} | ${ENEMY_EXPERIENCE_REWARD[kind]} | ${formatSpawn(entry.spawn)} | ${entry.behavior} |`;
	});
	return [
		"## 敵一覧",
		"",
		"全ての敵は眠った状態で出現し、隣接または視界内で毎ターン確率で目を覚ます。眠っている敵への攻撃は3倍ダメージの不意打ちになる(モンスターハウスの敵だけは最初から警戒済み)。",
		"",
		"| 絵文字 | 名前 | HP | 攻撃 | 行動/ターン | 経験値 | 出現 | 習性 |",
		"|---|---|---|---|---|---|---|---|",
		...rows,
	].join("\n");
};

const buildItemSection = (): string => {
	const rows = CATEGORY_ORDER.flatMap((category) =>
		ITEM_KIND_VALUES.filter(
			(kind) => ITEM_CATALOG[kind].category === category,
		).map((kind) => {
			const entry = ITEM_CATALOG[kind];
			return `| ${ITEM_GLYPHS[kind].glyph} | ${entry.catalogName} | ${entry.category} | ${resolveItemDisplayName(kind, [])} | ${formatSpawn(entry.spawn)} | ${entry.effect} |`;
		}),
	);
	return [
		"## アイテム一覧",
		"",
		"「拾った時の表示」が名前と違うものは、使う(または識別する)まで正体が分からない。薬は種類単位の鑑定制で、一度正体が判明すればそのランでは以後実名表示になる。",
		"",
		"| 絵文字 | 名前 | 分類 | 拾った時の表示 | 出現 | 効果 |",
		"|---|---|---|---|---|---|",
		...rows,
	].join("\n");
};

const buildTrapSection = (): string => {
	const rows = TRAP_KIND_VALUES.map((kind) => {
		const entry = TRAP_CATALOG[kind];
		return `| ${TRAP_NAMES[kind]} | ${formatSpawn(entry.spawn)} | ${entry.effect} |`;
	});
	return [
		"## わな一覧",
		"",
		"わなは踏むまで見えず、一度発動すると消える。浮遊中はどのわなも発動しない。部屋の内側(出入り口から離れたマス)にだけ配置される。",
		"",
		"| 名前 | 出現 | 効果 |",
		"|---|---|---|",
		...rows,
	].join("\n");
};

/** The complete docs/catalog.md content — see the header comment for the freshness contract. */
export const buildCatalogMarkdown = (): string =>
	[
		"# emoji-rogue カタログ(敵・アイテム・わな)",
		"",
		"<!-- GENERATED by scripts/generate-catalog.mjs — 手で編集しない。更新は `npm run docs:catalog`(catalog.test.tsが鮮度を強制する) -->",
		"",
		buildEnemySection(),
		"",
		buildItemSection(),
		"",
		buildTrapSection(),
		"",
	].join("\n");
