import { at } from "../../indexing.js";
import { createDiggerMap } from "../../map/digger.js";
import { getRoomCenter } from "../../map/features.js";
import type { Rng } from "../../rng.js";
import { GOAL_FLOOR } from "../balance.js";
import { buildEmptyColumns } from "../columns.js";
import type {
	Enemy,
	GoldPile,
	Item,
	Position,
	Stairs,
	Trap,
} from "../state.js";
import { drawFloorEnemies } from "./enemies.js";
import { drawFloorItems } from "./items.js";
import { collectSpawnPool, drawSpawnTile } from "./spawnPool.js";

/** Everything one dungeon floor is made of, before it becomes game state. */
export interface FloorLayout {
	readonly terrain: number[][];
	readonly player: Position;
	readonly enemies: readonly Enemy[];
	readonly items: readonly Item[];
	readonly goldPiles: readonly GoldPile[];
	readonly traps: readonly Trap[];
	readonly stairs: Stairs;
	/** Only set when this layout is GOAL_FLOOR — see buildFloorLayout. */
	readonly amulet: Position | undefined;
}

/**
 * One dungeon floor, generated by consuming (and thereby advancing) `rng`:
 * digger terrain, the player at the center of the first room, the enemies of
 * drawFloorEnemies (floorEnemies.ts), a staircase, and the items, gold and
 * traps of drawFloorItems (floorItems.ts), all drawn from the spawn pool.
 * Nothing shares a tile with anything else unless the pool ran dry (tiny
 * fully-visible maps). `stairsDirection` sets the generated staircase's
 * direction, except on GOAL_FLOOR, where it is always forced to "up" (there
 * is nothing lower) and the Amulet of Yendor spawns instead of nothing —
 * guaranteed, not a percent-chance draw like the other items.
 */
export const buildFloorLayout = (
	width: number,
	height: number,
	rng: Rng,
	floor: number,
	stairsDirection: "up" | "down",
): FloorLayout => {
	const columns = buildEmptyColumns(width);
	const dungeon = createDiggerMap(width, height, rng).create((x, y, value) => {
		at(columns, x)[y] = value;
	});

	const firstRoom = dungeon.getRooms()[0];
	if (firstRoom === undefined) {
		throw new Error("unreachable: digger always digs at least one room");
	}
	const [playerX, playerY] = getRoomCenter(firstRoom);
	const player: Position = { x: playerX, y: playerY };

	const pool = collectSpawnPool(columns, player);
	const enemies = drawFloorEnemies(
		dungeon.getRooms(),
		firstRoom,
		pool,
		rng,
		floor,
	);

	const remaining = pool.length > 0 ? pool : collectSpawnPool(columns, player);
	const direction = floor === GOAL_FLOOR ? "up" : stairsDirection;
	const stairs: Stairs = { ...drawSpawnTile(remaining, rng), direction };
	const amulet: Position | undefined =
		floor === GOAL_FLOOR ? drawSpawnTile(remaining, rng) : undefined;

	const { items, goldPiles, traps } = drawFloorItems(remaining, rng, floor);

	return {
		terrain: columns,
		player,
		enemies,
		items,
		goldPiles,
		traps,
		stairs,
		amulet,
	};
};
