import { at } from "../../indexing.js";
import { getRoomCenter, type Room } from "../../map/features.js";
import { createRogueMap } from "../../map/rogue.js";
import type { Rng } from "../../rng.js";
import { GOAL_FLOOR } from "../balance.js";
import { buildEmptyColumns } from "../columns.js";
import type {
	Enemy,
	GoldPile,
	Item,
	Position,
	Stairs,
	Trap,
} from "../state.js";
import { drawFloorEnemies } from "./enemies.js";
import { drawFloorItems } from "./items.js";
import {
	collectSpawnPool,
	drawSpawnTile,
	drawSpawnTileWhere,
	isRoomTileAwayFromDoors,
} from "./spawnPool.js";

/** Everything one dungeon floor is made of, before it becomes game state. */
export interface FloorLayout {
	readonly terrain: number[][];
	readonly player: Position;
	readonly enemies: readonly Enemy[];
	readonly items: readonly Item[];
	readonly goldPiles: readonly GoldPile[];
	readonly traps: readonly Trap[];
	readonly stairs: Stairs;
	/** Only set when this layout is GOAL_FLOOR — see buildFloorLayout. */
	readonly amulet: Position | undefined;
	/** The digger's room rectangles — kept for placement checks and tests; never part of GameState. */
	readonly rooms: readonly Room[];
	/** `nextItemId` after this floor's equipment spawns each consumed one — see drawFloorItems. */
	readonly nextItemId: number;
}

/**
 * One dungeon floor, generated by consuming (and thereby advancing) `rng`:
 * digger terrain, the player at the center of the first room, the enemies of
 * drawFloorEnemies (floorEnemies.ts), a staircase, and the items, gold and
 * traps of drawFloorItems (floorItems.ts), all drawn from the spawn pool.
 * Nothing shares a tile with anything else unless the pool ran dry (tiny
 * fully-visible maps).
 *
 * The staircase and every trap only land on room-interior tiles away from
 * doorways (see isRoomTileAwayFromDoors) — stepping on stairs descends
 * immediately, so a staircase in a corridor would physically block passage.
 * The staircase falls back to any tile if no such tile is pooled (degenerate
 * maps); traps are simply skipped then. `stairsDirection` sets the generated
 * staircase's direction, except on GOAL_FLOOR, where it is always forced to
 * "up" (there is nothing lower) and the Amulet of Yendor spawns instead of
 * nothing — guaranteed, not a percent-chance draw like the other items.
 */
export const buildFloorLayout = (
	width: number,
	height: number,
	rng: Rng,
	floor: number,
	stairsDirection: "up" | "down",
	nextItemId: number,
): FloorLayout => {
	const columns = buildEmptyColumns(width);
	const dungeon = createRogueMap(width, height, rng).create((x, y, value) => {
		at(columns, x)[y] = value;
	});
	const rooms = dungeon.getRooms();

	const firstRoom = rooms[0];
	if (firstRoom === undefined) {
		throw new Error(
			"unreachable: the rogue generator always carves at least one room",
		);
	}
	const [playerX, playerY] = getRoomCenter(firstRoom);
	const player: Position = { x: playerX, y: playerY };

	const pool = collectSpawnPool(columns, player);
	const enemies = drawFloorEnemies(pool, rng, floor);

	const remaining = pool.length > 0 ? pool : collectSpawnPool(columns, player);
	const isWalkAroundTile = (position: Position): boolean =>
		isRoomTileAwayFromDoors(rooms, position);
	const direction = floor === GOAL_FLOOR ? "up" : stairsDirection;
	const stairs: Stairs = {
		...(drawSpawnTileWhere(remaining, rng, isWalkAroundTile) ??
			drawSpawnTile(remaining, rng)),
		direction,
	};
	const amulet: Position | undefined =
		floor === GOAL_FLOOR ? drawSpawnTile(remaining, rng) : undefined;

	const {
		items,
		goldPiles,
		traps,
		nextItemId: nextItemIdAfterFloor,
	} = drawFloorItems(remaining, rng, floor, isWalkAroundTile, nextItemId);

	return {
		terrain: columns,
		player,
		enemies,
		items,
		goldPiles,
		traps,
		stairs,
		amulet,
		rooms,
		nextItemId: nextItemIdAfterFloor,
	};
};
